export default {
  rootUrl: 'https://haller-api-v2.herokuapp.com/api/',
  env: 'staging',
  jwtSecret: '0a6b944d-d2fb-46fc-a85e-0295c986cd9f',
  db: 'mongodb://haller:Haller2017@ds145868.mlab.com:45868/haller-app-sandbox',
  mailgun: {
    key: 'key-123e941659eb0511afc01ddf7b60df3a',
    domain: 'mg.gohaller.com'
  },
  port: "4040",
  websiteUrl: 'portal.gohaller.com',
  inviteCode: 'gohallerku',
  baCodes: ['andsar',
    'allche',
    'heimar',
    'cohshe',
    'kememi',
    'wonoli',
    'bufpai',
    'lantay',
    'boutai',
    'ricril',
    'wilbri',
    'mersar',
    'prirac',
    'dukrac',
    'wismol',
    'hieemi',
    'clelau',
    'neesop',
    'samnat',
    'altkel',
    'halmck',
    'mcmcou',
    'densar',
    'seanic',
    'salane',
    'mclbri',
    'pieisa',
    'schcal',
    'petsha',
    'ahrbri',
    'swysyd',
    'pottes',
    'gilhay',
    'fosmad',
    'kieell',
    'fiocla',
    'veajod',
    'benkit',
    'kimliz',
    'scavic',
    'gunemm',
    'staemm',
    'bursop',
    'mellau',
    'meebla',
    'bromar',
    'torcam',
    'schemi',
    'mcncri',
    'breell',
    'rocava',
    'galeri',
    'mcstes',
    'panjen',
    'clecel',
    'hefcar',
    'wolmck',
    'osthea',
    'stolau',
    'erioli',
    'leigre',
    'hownat',
    'cotcam',
    'cohsum',
    'scogra']
};
